version: '3.8'

services:
  qodo-embed-api:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: qodo_embed_api
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    # volumes: # Uncomment for development to reflect code changes without rebuilding
    #   - ./main.py:/app/main.py
    restart: unless-stopped
    # healthcheck: # Optional basic healthcheck
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s # Give time for model to load

    # --- GPU Support (Uncomment and configure if you have an NVIDIA GPU and want to use it) ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1 # or 'all'
    #           capabilities: [gpu]
    # Make sure your Dockerfile and PyTorch installation are set up for GPU (e.g., nvidia/cuda base image, torch with CUDA).
    # You'll also need nvidia-docker2 and the NVIDIA Container Toolkit installed on your host.
    # --- End GPU Support ---

networks:
  default:
    name: qodo_network